//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.9 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2026.10.06 at 02:51:37 PM WEST
//

package test1.JAVAClasses;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlIDREF;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType>
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element ref="{}host_institution"/>
 *         <element ref="{}total_citations"/>
 *         <element ref="{}citations_current_year"/>
 *         <element ref="{}article" maxOccurs="unbounded"/>
 *       </sequence>
 *       <attribute name="authorRef" use="required" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
 *       <attribute name="interestRefs" use="required" type="{http://www.w3.org/2001/XMLSchema}IDREFS" />
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "hostInstitution",
    "totalCitations",
    "citationsCurrentYear",
    "article"
})
@XmlRootElement(name = "investigator")
public class Investigator {

    @XmlElement(name = "host_institution", required = true)
    protected String hostInstitution;
    @XmlElement(name = "total_citations", required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger totalCitations;
    @XmlElement(name = "citations_current_year", required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger citationsCurrentYear;
    @XmlElement(required = true)
    protected List<Article> article;
    @XmlAttribute(name = "authorRef", required = true)
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object authorRef;
    @XmlAttribute(name = "interestRefs", required = true)
    @XmlIDREF
    @XmlSchemaType(name = "IDREFS")
    protected List<Object> interestRefs;

    /**
     * Gets the value of the hostInstitution property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHostInstitution() {
        return hostInstitution;
    }

    /**
     * Sets the value of the hostInstitution property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHostInstitution(String value) {
        this.hostInstitution = value;
    }

    /**
     * Gets the value of the totalCitations property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTotalCitations() {
        return totalCitations;
    }

    /**
     * Sets the value of the totalCitations property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTotalCitations(BigInteger value) {
        this.totalCitations = value;
    }

    /**
     * Gets the value of the citationsCurrentYear property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCitationsCurrentYear() {
        return citationsCurrentYear;
    }

    /**
     * Sets the value of the citationsCurrentYear property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCitationsCurrentYear(BigInteger value) {
        this.citationsCurrentYear = value;
    }

    /**
     * Gets the value of the article property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore, any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the article property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getArticle().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Article }
     * </p>
     * 
     * 
     * @return
     *     The value of the article property.
     */
    public List<Article> getArticle() {
        if (article == null) {
            article = new ArrayList<>();
        }
        return this.article;
    }

    /**
     * Gets the value of the authorRef property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getAuthorRef() {
        return authorRef;
    }

    /**
     * Sets the value of the authorRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setAuthorRef(Object value) {
        this.authorRef = value;
    }

    /**
     * Gets the value of the interestRefs property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore, any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the interestRefs property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getInterestRefs().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * </p>
     * 
     * 
     * @return
     *     The value of the interestRefs property.
     */
    public List<Object> getInterestRefs() {
        if (interestRefs == null) {
            interestRefs = new ArrayList<>();
        }
        return this.interestRefs;
    }

}
