//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.9 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2026.10.06 at 02:51:37 PM WEST
//

package test1.JAVAClasses;

import java.math.BigInteger;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlElementDecl;
import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the JAVAClasses package. 
 * <p>An ObjectFactory allows you to programmatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private static final QName _Name_QNAME = new QName("", "name");
    private static final QName _HostInstitution_QNAME = new QName("", "host_institution");
    private static final QName _TotalCitations_QNAME = new QName("", "total_citations");
    private static final QName _CitationsCurrentYear_QNAME = new QName("", "citations_current_year");
    private static final QName _Title_QNAME = new QName("", "title");
    private static final QName _Date_QNAME = new QName("", "date");
    private static final QName _Journal_QNAME = new QName("", "journal");
    private static final QName _Publisher_QNAME = new QName("", "publisher");
    private static final QName _ArticleCitations_QNAME = new QName("", "article_citations");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: JAVAClasses
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Scholar }
     * 
     * @return
     *     the new instance of {@link Scholar }
     */
    public Scholar createScholar() {
        return new Scholar();
    }

    /**
     * Create an instance of {@link Authors }
     * 
     * @return
     *     the new instance of {@link Authors }
     */
    public Authors createAuthors() {
        return new Authors();
    }

    /**
     * Create an instance of {@link Author }
     * 
     * @return
     *     the new instance of {@link Author }
     */
    public Author createAuthor() {
        return new Author();
    }

    /**
     * Create an instance of {@link Interests }
     * 
     * @return
     *     the new instance of {@link Interests }
     */
    public Interests createInterests() {
        return new Interests();
    }

    /**
     * Create an instance of {@link Interest }
     * 
     * @return
     *     the new instance of {@link Interest }
     */
    public Interest createInterest() {
        return new Interest();
    }

    /**
     * Create an instance of {@link Investigators }
     * 
     * @return
     *     the new instance of {@link Investigators }
     */
    public Investigators createInvestigators() {
        return new Investigators();
    }

    /**
     * Create an instance of {@link Investigator }
     * 
     * @return
     *     the new instance of {@link Investigator }
     */
    public Investigator createInvestigator() {
        return new Investigator();
    }

    /**
     * Create an instance of {@link Article }
     * 
     * @return
     *     the new instance of {@link Article }
     */
    public Article createArticle() {
        return new Article();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "name")
    public JAXBElement<String> createName(String value) {
        return new JAXBElement<>(_Name_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "host_institution")
    public JAXBElement<String> createHostInstitution(String value) {
        return new JAXBElement<>(_HostInstitution_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "total_citations")
    public JAXBElement<BigInteger> createTotalCitations(BigInteger value) {
        return new JAXBElement<>(_TotalCitations_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "citations_current_year")
    public JAXBElement<BigInteger> createCitationsCurrentYear(BigInteger value) {
        return new JAXBElement<>(_CitationsCurrentYear_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "title")
    public JAXBElement<String> createTitle(String value) {
        return new JAXBElement<>(_Title_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "date")
    public JAXBElement<XMLGregorianCalendar> createDate(XMLGregorianCalendar value) {
        return new JAXBElement<>(_Date_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "journal")
    public JAXBElement<String> createJournal(String value) {
        return new JAXBElement<>(_Journal_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "publisher")
    public JAXBElement<String> createPublisher(String value) {
        return new JAXBElement<>(_Publisher_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "article_citations")
    public JAXBElement<BigInteger> createArticleCitations(BigInteger value) {
        return new JAXBElement<>(_ArticleCitations_QNAME, BigInteger.class, null, value);
    }

}
