//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.9 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2026.10.06 at 02:51:37 PM WEST
//

package test1.JAVAClasses;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType>
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element ref="{}authors"/>
 *         <element ref="{}interests"/>
 *         <element ref="{}investigators"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "authors",
    "interests",
    "investigators"
})
@XmlRootElement(name = "scholar")
public class Scholar {

    @XmlElement(required = true)
    protected Authors authors;
    @XmlElement(required = true)
    protected Interests interests;
    @XmlElement(required = true)
    protected Investigators investigators;

    /**
     * Gets the value of the authors property.
     * 
     * @return
     *     possible object is
     *     {@link Authors }
     *     
     */
    public Authors getAuthors() {
        return authors;
    }

    /**
     * Sets the value of the authors property.
     * 
     * @param value
     *     allowed object is
     *     {@link Authors }
     *     
     */
    public void setAuthors(Authors value) {
        this.authors = value;
    }

    /**
     * Gets the value of the interests property.
     * 
     * @return
     *     possible object is
     *     {@link Interests }
     *     
     */
    public Interests getInterests() {
        return interests;
    }

    /**
     * Sets the value of the interests property.
     * 
     * @param value
     *     allowed object is
     *     {@link Interests }
     *     
     */
    public void setInterests(Interests value) {
        this.interests = value;
    }

    /**
     * Gets the value of the investigators property.
     * 
     * @return
     *     possible object is
     *     {@link Investigators }
     *     
     */
    public Investigators getInvestigators() {
        return investigators;
    }

    /**
     * Sets the value of the investigators property.
     * 
     * @param value
     *     allowed object is
     *     {@link Investigators }
     *     
     */
    public void setInvestigators(Investigators value) {
        this.investigators = value;
    }

}
