//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.9 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2026.09.24 at 04:57:22 PM WEST
//

package auxiliar;

import java.math.BigInteger;
import javax.xml.namespace.QName;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlElementDecl;
import jakarta.xml.bind.annotation.XmlRegistry;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the auxiliar package. 
 * <p>An ObjectFactory allows you to programmatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private static final QName _Authors_QNAME = new QName("", "Authors");
    private static final QName _Publicationdate_QNAME = new QName("", "Publicationdate");
    private static final QName _Description_QNAME = new QName("", "description");
    private static final QName _Issue_QNAME = new QName("", "issue");
    private static final QName _Journal_QNAME = new QName("", "journal");
    private static final QName _Pages_QNAME = new QName("", "pages");
    private static final QName _Publisher_QNAME = new QName("", "publisher");
    private static final QName _Totalcitations_QNAME = new QName("", "totalcitations");
    private static final QName _Volume_QNAME = new QName("", "volume");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: auxiliar
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Scholar }
     * 
     * @return
     *     the new instance of {@link Scholar }
     */
    public Scholar createScholar() {
        return new Scholar();
    }

    /**
     * Create an instance of {@link Investigators }
     * 
     * @return
     *     the new instance of {@link Investigators }
     */
    public Investigators createInvestigators() {
        return new Investigators();
    }

    /**
     * Create an instance of {@link Articles }
     * 
     * @return
     *     the new instance of {@link Articles }
     */
    public Articles createArticles() {
        return new Articles();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "Authors")
    public JAXBElement<String> createAuthors(String value) {
        return new JAXBElement<>(_Authors_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "Publicationdate")
    public JAXBElement<String> createPublicationdate(String value) {
        return new JAXBElement<>(_Publicationdate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "description")
    public JAXBElement<String> createDescription(String value) {
        return new JAXBElement<>(_Description_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "issue")
    public JAXBElement<BigInteger> createIssue(BigInteger value) {
        return new JAXBElement<>(_Issue_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "journal")
    public JAXBElement<String> createJournal(String value) {
        return new JAXBElement<>(_Journal_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "pages")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createPages(String value) {
        return new JAXBElement<>(_Pages_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "publisher")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createPublisher(String value) {
        return new JAXBElement<>(_Publisher_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "totalcitations")
    public JAXBElement<String> createTotalcitations(String value) {
        return new JAXBElement<>(_Totalcitations_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "volume")
    public JAXBElement<BigInteger> createVolume(BigInteger value) {
        return new JAXBElement<>(_Volume_QNAME, BigInteger.class, null, value);
    }

}
