//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.9 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2026.09.24 at 04:57:22 PM WEST
//

package auxiliar;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType>
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element ref="{}investigators"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "investigators"
})
@XmlRootElement(name = "scholar")
public class Scholar {

    @XmlElement(required = true)
    protected Investigators investigators;

    /**
     * Gets the value of the investigators property.
     * 
     * @return
     *     possible object is
     *     {@link Investigators }
     *     
     */
    public Investigators getInvestigators() {
        return investigators;
    }

    /**
     * Sets the value of the investigators property.
     * 
     * @param value
     *     allowed object is
     *     {@link Investigators }
     *     
     */
    public void setInvestigators(Investigators value) {
        this.investigators = value;
    }

}
