//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.9 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2026.10.01 at 04:28:26 PM WEST
//

package JAVAClasses;

import java.io.Serializable;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlElementRef;
import jakarta.xml.bind.annotation.XmlElementRefs;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType>
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element ref="{}host_institution"/>
 *         <element ref="{}interests"/>
 *         <element ref="{}total_citations"/>
 *         <element ref="{}number_of_citations_in_2026"/>
 *         <choice maxOccurs="unbounded">
 *           <element ref="{}article"/>
 *           <element ref="{}article_citations"/>
 *           <element ref="{}authors"/>
 *           <element ref="{}date"/>
 *           <element ref="{}journal"/>
 *         </choice>
 *       </sequence>
 *       <attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "hostInstitution",
    "interests",
    "totalCitations",
    "numberOfCitationsIn2026",
    "articleOrArticleCitationsOrAuthors"
})
@XmlRootElement(name = "investigador")
public class Investigador {

    @XmlElement(name = "host_institution", required = true)
    protected String hostInstitution;
    @XmlElement(required = true)
    protected String interests;
    @XmlElement(name = "total_citations", required = true)
    protected BigInteger totalCitations;
    @XmlElement(name = "number_of_citations_in_2026", required = true)
    protected BigInteger numberOfCitationsIn2026;
    @XmlElementRefs({
        @XmlElementRef(name = "article", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "article_citations", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "authors", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "date", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "journal", type = JAXBElement.class, required = false)
    })
    protected List<JAXBElement<? extends Serializable>> articleOrArticleCitationsOrAuthors;
    @XmlAttribute(name = "name", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String name;

    /**
     * Gets the value of the hostInstitution property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHostInstitution() {
        return hostInstitution;
    }

    /**
     * Sets the value of the hostInstitution property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHostInstitution(String value) {
        this.hostInstitution = value;
    }

    /**
     * Gets the value of the interests property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInterests() {
        return interests;
    }

    /**
     * Sets the value of the interests property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInterests(String value) {
        this.interests = value;
    }

    /**
     * Gets the value of the totalCitations property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTotalCitations() {
        return totalCitations;
    }

    /**
     * Sets the value of the totalCitations property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTotalCitations(BigInteger value) {
        this.totalCitations = value;
    }

    /**
     * Gets the value of the numberOfCitationsIn2026 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumberOfCitationsIn2026() {
        return numberOfCitationsIn2026;
    }

    /**
     * Sets the value of the numberOfCitationsIn2026 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumberOfCitationsIn2026(BigInteger value) {
        this.numberOfCitationsIn2026 = value;
    }

    /**
     * Gets the value of the articleOrArticleCitationsOrAuthors property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore, any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the articleOrArticleCitationsOrAuthors property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getArticleOrArticleCitationsOrAuthors().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * </p>
     * 
     * 
     * @return
     *     The value of the articleOrArticleCitationsOrAuthors property.
     */
    public List<JAXBElement<? extends Serializable>> getArticleOrArticleCitationsOrAuthors() {
        if (articleOrArticleCitationsOrAuthors == null) {
            articleOrArticleCitationsOrAuthors = new ArrayList<>();
        }
        return this.articleOrArticleCitationsOrAuthors;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

}
