//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.9 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2026.10.01 at 04:28:26 PM WEST
//

package JAVAClasses;

import java.math.BigInteger;
import javax.xml.namespace.QName;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlElementDecl;
import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the JAVAClasses package. 
 * <p>An ObjectFactory allows you to programmatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private static final QName _HostInstitution_QNAME = new QName("", "host_institution");
    private static final QName _Interests_QNAME = new QName("", "interests");
    private static final QName _TotalCitations_QNAME = new QName("", "total_citations");
    private static final QName _NumberOfCitationsIn2026_QNAME = new QName("", "number_of_citations_in_2026");
    private static final QName _Article_QNAME = new QName("", "article");
    private static final QName _ArticleCitations_QNAME = new QName("", "article_citations");
    private static final QName _Authors_QNAME = new QName("", "authors");
    private static final QName _Date_QNAME = new QName("", "date");
    private static final QName _Journal_QNAME = new QName("", "journal");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: JAVAClasses
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Scholar }
     * 
     * @return
     *     the new instance of {@link Scholar }
     */
    public Scholar createScholar() {
        return new Scholar();
    }

    /**
     * Create an instance of {@link Investigador }
     * 
     * @return
     *     the new instance of {@link Investigador }
     */
    public Investigador createInvestigador() {
        return new Investigador();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "host_institution")
    public JAXBElement<String> createHostInstitution(String value) {
        return new JAXBElement<>(_HostInstitution_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "interests")
    public JAXBElement<String> createInterests(String value) {
        return new JAXBElement<>(_Interests_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "total_citations")
    public JAXBElement<BigInteger> createTotalCitations(BigInteger value) {
        return new JAXBElement<>(_TotalCitations_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "number_of_citations_in_2026")
    public JAXBElement<BigInteger> createNumberOfCitationsIn2026(BigInteger value) {
        return new JAXBElement<>(_NumberOfCitationsIn2026_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "article")
    public JAXBElement<String> createArticle(String value) {
        return new JAXBElement<>(_Article_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "article_citations")
    public JAXBElement<BigInteger> createArticleCitations(BigInteger value) {
        return new JAXBElement<>(_ArticleCitations_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "authors")
    public JAXBElement<String> createAuthors(String value) {
        return new JAXBElement<>(_Authors_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "date")
    public JAXBElement<String> createDate(String value) {
        return new JAXBElement<>(_Date_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "journal")
    public JAXBElement<String> createJournal(String value) {
        return new JAXBElement<>(_Journal_QNAME, String.class, null, value);
    }

}
