<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="scholar">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="investigador"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="investigador">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="host_institution"/>
        <xs:element ref="interests"/>
        <xs:element ref="total_citations"/>
        <xs:element ref="number_of_citations_in_2026"/>
        <xs:choice maxOccurs="unbounded">
          <xs:element ref="article"/>
          <xs:element ref="article_citations"/>
          <xs:element ref="authors"/>
          <xs:element ref="date"/>
          <xs:element ref="journal"/>
        </xs:choice>
      </xs:sequence>
      <xs:attribute name="name" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="host_institution" type="xs:string"/>
  <xs:element name="interests" type="xs:string"/>
  <xs:element name="total_citations" type="xs:integer"/>
  <xs:element name="number_of_citations_in_2026" type="xs:integer"/>
  <xs:element name="article" type="xs:string"/>
  <xs:element name="article_citations" type="xs:integer"/>
  <xs:element name="authors" type="xs:string"/>
  <xs:element name="date" type="xs:string"/>
  <xs:element name="journal" type="xs:string"/>
</xs:schema>
