<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

  <xs:element name="scholar">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="authors"/>
        <xs:element ref="interests"/>
        <xs:element ref="investigators"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="authors">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="author"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="author">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="name"/>
      </xs:sequence>
      <xs:attribute name="id" use="required" type="xs:ID"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="name" type="xs:string"/>

  <xs:element name="interests">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="interest"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="interest">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute name="id" use="required" type="xs:ID"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>

  <xs:element name="investigators">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="investigator"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="investigator">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="host_institution"/>
        <xs:element ref="total_citations"/>
        <xs:element ref="citations_current_year"/>
        <xs:element maxOccurs="unbounded" ref="article"/>
      </xs:sequence>
      <xs:attribute name="authorRef" use="required" type="xs:IDREF"/>
      <xs:attribute name="interestRefs" use="required" type="xs:IDREFS"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="host_institution" type="xs:string"/>
  <xs:element name="total_citations" type="xs:nonNegativeInteger"/>
  <xs:element name="citations_current_year" type="xs:nonNegativeInteger"/>

  <xs:element name="article">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="title"/>
        <xs:element ref="date"/>
        <xs:element ref="journal"/>
        <xs:element ref="publisher"/>
        <xs:element ref="article_citations"/>
      </xs:sequence>
      <xs:attribute name="id" use="required" type="xs:ID"/>
      <xs:attribute name="authorRefs" use="required" type="xs:IDREFS"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="title" type="xs:string"/>
  <xs:element name="date" type="xs:string"/>
  <xs:element name="journal" type="xs:string"/>
  <xs:element name="publisher" type="xs:string"/>
  <xs:element name="article_citations" type="xs:nonNegativeInteger"/>
</xs:schema>
